name: Sign MSIX

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore certificate
        shell: powershell
        env:
          CERT_BASE64: ${{ secrets.MSIX_CERT_BASE64 }}
        run: |
          $bytes = [System.Convert]::FromBase64String($env:CERT_BASE64)
          [System.IO.File]::WriteAllBytes("cert.pfx", $bytes)

      - name: Sign MSIX
        shell: powershell
        env:
          CERT_PASS: ${{ secrets.MSIX_CERT_PASSWORD }}
        run: |
          $signtool = "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe"

          if (-not (Test-Path $signtool)) {
            throw "signtool.exe n√£o encontrado"
          }

          & $signtool sign `
            /fd SHA256 `
            /f cert.pfx `
            /p $env:CERT_PASS `
            SimpliPlay.UWP_1.0.1.0_x64.msix

      - name: Upload signed MSIX
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: SimpliPlay.UWP_1.0.1.0_x64.msix
